### ISSUE TITLE
VCF files

### ISSUE THREAD

**Issue by tomouellette** [GeorgetteTanner/benchmarking#1]
Hi Georgette,

I'm just looking for some ground truth clone information and it looks like your data you generated would work well. However, I was wondering where I can download the VCF files? I can't seem to locate them.

Thanks,
Tom

**Comment by GeorgetteTanner** [comment]
Hi Tom

Thanks for your message. The VCF files are fairly large so they're only available as part of a release. You can download them from here: https://github.com/GeorgetteTanner/benchmarking/releases/tag/v1.0 

Let me know if you have any issues using them.

Best,
Georgette

**Comment by tomouellette** [comment]
Awesome, thank you for the fast reply Georgette! I totally missed the release link... my bad
